services:
  app:
    environment:
      - DEBUG_MODE=true
      - PYTHONUNBUFFERED=1 # make sure logs are printed to the console
    build:
      context: .
      dockerfile: Dockerfile
    image: eyetracking-app:latest
    ports:
      - "8000:8000"
    gpus:
      - driver: nvidia
        count: all
    volumes:
      - ./src:/app/src
      - ./checkpoints:/app/checkpoints
      - ./database.db:/app/database.db
      - ./data:/app/data
      # cache Poetry & pip downloads between container restarts
      - poetry_cache:/root/.cache/pypoetry
      - pip_cache:/root/.cache/pip
    # start Uvicorn in reload mode, listening on all interfaces
    command: >
      poetry run uvicorn src.main:app
        --reload
        --host 0.0.0.0
        --port 8000

volumes:
  poetry_cache:
  pip_cache:
